 #Deploy aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaopeso
spec:
   replicas: 1
   selector:
     matchLabels:
       app: conversaopeso
   template:
     metadata:
       labels:
         app: conversaopeso
     spec:
       containers:
         - name: conversaopeso
           image: thiagogomestec/conversao-peso:latest
           ports:
             - containerPort: 80   
---
# Service da aplicação Web
apiVersion: v1
kind: Service
metadata:
  name: conversaopeso
spec: 
  selector:
    app: conversaopeso
  ports:
    - port: 80
      targetPort: 80
     # protocol: TCP
     # name: http
      nodePort: 30001
  type: LoadBalancer


